### ISSUE TITLE
jsdoc fails on Object.create with constructor property

### ISSUE THREAD

**Issue by blixt** [jsdoc/jsdoc#103]
The following code causes issues:

```
// Simple inheritance model with correct constructor
function Test() {}
function Test2() { Test.call(this); }
Test2.prototype = Object.create(Test.prototype, {constructor: {value: Test2}});
```

It works fine when using Rhino's console directly, but through JSDoc it causes the following error, which references jsdoc generated code:

```
org.mozilla.javascript.EcmaError: TypeError: Cannot find function replace in object function Object() { [native code for Object.Object, arity=1] }
.
    at org.mozilla.javascript.ScriptRuntime.constructError(ScriptRuntime.java:3785)
    at org.mozilla.javascript.ScriptRuntime.constructError(ScriptRuntime.java:3763)
    at org.mozilla.javascript.ScriptRuntime.typeError(ScriptRuntime.java:3791)
    at org.mozilla.javascript.ScriptRuntime.typeError2(ScriptRuntime.java:3810)
    at org.mozilla.javascript.ScriptRuntime.notFunctionError(ScriptRuntime.java:3881)
    at org.mozilla.javascript.ScriptRuntime.getPropFunctionAndThisHelper(ScriptRuntime.java:2360)
    at org.mozilla.javascript.ScriptRuntime.getPropFunctionAndThis(ScriptRuntime.java:2327)
    at org.mozilla.javascript.gen.file__Users_blixt_src_jsdoc_rhino_modules_jsdoc_tag_js_15._c_trim_2(Unknown Source)
    at org.mozilla.javascript.gen.file__Users_blixt_src_jsdoc_rhino_modules_jsdoc_tag_js_15.call(Unknown Source)
    at org.mozilla.javascript.optimizer.OptRuntime.callName(OptRuntime.java:97)
    at org.mozilla.javascript.gen.file__Users_blixt_src_jsdoc_rhino_modules_jsdoc_tag_js_15._c_anonymous_1(Unknown Source)
    at org.mozilla.javascript.gen.file__Users_blixt_src_jsdoc_rhino_modules_jsdoc_tag_js_15.call(Unknown Source)
    at org.mozilla.javascript.BaseFunction.construct(BaseFunction.java:369)
    at org.mozilla.javascript.ScriptRuntime.newObject(ScriptRuntime.java:2440)
    at org.mozilla.javascript.gen.file__Users_blixt_src_jsdoc_rhino_modules_jsdoc_doclet_js_14._c_anonymous_3(Unknown Source)
    at org.mozilla.javascript.gen.file__Users_blixt_src_jsdoc_rhino_modules_jsdoc_doclet_js_14.call(Unknown Source)
    at org.mozilla.javascript.optimizer.OptRuntime.call2(OptRuntime.java:76)
    at org.mozilla.javascript.gen.file__Users_blixt_src_jsdoc_rhino_modules_jsdoc_src_handlers_js_13._c_newSymbolDoclet_4(Unknown Source)
    at org.mozilla.javascript.gen.file__Users_blixt_src_jsdoc_rhino_modules_jsdoc_src_handlers_js_13.call(Unknown Source)
    at org.mozilla.javascript.ScriptRuntime.applyOrCall(ScriptRuntime.java:2521)
    at org.mozilla.javascript.BaseFunction.execIdCall(BaseFunction.java:300)
    at org.mozilla.javascript.IdFunctionObject.call(IdFunctionObject.java:129)
    at org.mozilla.javascript.optimizer.OptRuntime.callN(OptRuntime.java:86)
    at org.mozilla.javascript.gen.file__Users_blixt_src_jsdoc_rhino_modules_jsdoc_src_handlers_js_13._c_anonymous_3(Unknown Source)
    at org.mozilla.javascript.gen.file__Users_blixt_src_jsdoc_rhino_modules_jsdoc_src_handlers_js_13.call(Unknown Source)
    at org.mozilla.javascript.ScriptRuntime.applyOrCall(ScriptRuntime.java:2521)
    at org.mozilla.javascript.BaseFunction.execIdCall(BaseFunction.java:300)
    at org.mozilla.javascript.IdFunctionObject.call(IdFunctionObject.java:129)
    at org.mozilla.javascript.optimizer.OptRuntime.call2(OptRuntime.java:76)
    at org.mozilla.javascript.gen.file__Users_blixt_src_jsdoc_node_modules_common_events_js_5._c_anonymous_2(Unknown Source)
    at org.mozilla.javascript.gen.file__Users_blixt_src_jsdoc_node_modules_common_events_js_5.call(Unknown Source)
    at org.mozilla.javascript.optimizer.OptRuntime.call1(OptRuntime.java:66)
    at org.mozilla.javascript.gen.file__Users_blixt_src_jsdoc_node_modules_common_events_js_5._c_anonymous_3(Unknown Source)
    at org.mozilla.javascript.gen.file__Users_blixt_src_jsdoc_node_modules_common_events_js_5.call(Unknown Source)
    at org.mozilla.javascript.optimizer.OptRuntime.callN(OptRuntime.java:86)
    at org.mozilla.javascript.gen.file__Users_blixt_src_jsdoc_rhino_modules_jsdoc_src_parser_js_7._c_visitNode_16(Unknown Source)
    at org.mozilla.javascript.gen.file__Users_blixt_src_jsdoc_rhino_modules_jsdoc_src_parser_js_7.call(Unknown Source)
    at org.mozilla.javascript.JavaAdapter.doCall(JavaAdapter.java:598)
    at org.mozilla.javascript.JavaAdapter.callMethod(JavaAdapter.java:573)
    at adapter1.visit(<adapter>)
    at org.mozilla.javascript.ast.InfixExpression.visit(InfixExpression.java:209)
    at org.mozilla.javascript.ast.ObjectLiteral.visit(ObjectLiteral.java:164)
    at org.mozilla.javascript.ast.FunctionCall.visit(FunctionCall.java:192)
    at org.mozilla.javascript.ast.VariableInitializer.visit(VariableInitializer.java:154)
    at org.mozilla.javascript.ast.VariableDeclaration.visit(VariableDeclaration.java:169)
    at org.mozilla.javascript.ast.ScriptNode.visit(ScriptNode.java:347)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:161)
    at org.mozilla.javascript.NativeJavaMethod.call(NativeJavaMethod.java:247)
    at org.mozilla.javascript.optimizer.OptRuntime.call1(OptRuntime.java:66)
    at org.mozilla.javascript.gen.file__Users_blixt_src_jsdoc_rhino_modules_jsdoc_src_parser_js_7._c_anonymous_8(Unknown Source)
    at org.mozilla.javascript.gen.file__Users_blixt_src_jsdoc_rhino_modules_jsdoc_src_parser_js_7.call(Unknown Source)
    at org.mozilla.javascript.optimizer.OptRuntime.call2(OptRuntime.java:76)
    at org.mozilla.javascript.gen.file__Users_blixt_src_jsdoc_rhino_modules_jsdoc_src_parser_js_7._c_anonymous_2(Unknown Source)
    at org.mozilla.javascript.gen.file__Users_blixt_src_jsdoc_rhino_modules_jsdoc_src_parser_js_7.call(Unknown Source)
    at org.mozilla.javascript.optimizer.OptRuntime.call2(OptRuntime.java:76)
    at org.mozilla.javascript.gen._Users_blixt_src_jsdoc_jsdoc_js_1._c_main_5(Unknown Source)
    at org.mozilla.javascript.gen._Users_blixt_src_jsdoc_jsdoc_js_1.call(Unknown Source)
    at org.mozilla.javascript.optimizer.OptRuntime.callName0(OptRuntime.java:108)
    at org.mozilla.javascript.gen._Users_blixt_src_jsdoc_jsdoc_js_1._c_script_0(Unknown Source)
    at org.mozilla.javascript.gen._Users_blixt_src_jsdoc_jsdoc_js_1.call(Unknown Source)
    at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:426)
    at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3178)
    at org.mozilla.javascript.gen._Users_blixt_src_jsdoc_jsdoc_js_1.call(Unknown Source)
    at org.mozilla.javascript.gen._Users_blixt_src_jsdoc_jsdoc_js_1.exec(Unknown Source)
    at org.mozilla.javascript.tools.shell.Main.evaluateScript(Main.java:654)
    at org.mozilla.javascript.tools.shell.Main.processFileSecure(Main.java:552)
    at org.mozilla.javascript.tools.shell.Main.processFile(Main.java:507)
    at org.mozilla.javascript.tools.shell.Main.processSource(Main.java:499)
    at org.mozilla.javascript.tools.shell.Main.processFiles(Main.java:215)
    at org.mozilla.javascript.tools.shell.Main$IProxy.run(Main.java:134)
    at org.mozilla.javascript.Context.call(Context.java:521)
    at org.mozilla.javascript.ContextFactory.call(ContextFactory.java:535)
    at org.mozilla.javascript.tools.shell.Main.exec(Main.java:198)
    at org.mozilla.javascript.tools.shell.Main.main(Main.java:174)
```

**Comment by zeuben** [comment]
related? https://github.com/krampstudio/grunt-jsdoc/issues/118

**Comment by hegemonic** [comment]
@zeuben This bug is ancient. There's no way it has anything to do with the grunt-jsdoc bug.
