### ISSUE TITLE
incomplete output when using babel-plugin-transform-flow-strip-types

### ISSUE THREAD

**Issue by hundekoerper** [jsdoc/jsdoc#1493]
Our codebase uses flow type annotations which forced me to use jsdoc-babel despite babylon being now integrated into JSDoc. Unfortunately when using the `transform-flow-strip-types`-plugin there is no output generated for methods of classes with type annotations. This was touched upon before [in this issue](https://github.com/jsdoc3/jsdoc/issues/1348), which brought me on the right track while debugging. 

As a workaround for now I pre-transform the code with `flow-remove-types`. This gives me the desired output.

### Input code

```js
// @flow
export default class SomeClass extends Parent {
  type = SOME_CLASS;

  _foo: Map<string, Object> = new Map();
  _bar = null;
  _baz = null;

  constructor(object: SomeObject, options: SomeOptions) {
    super(object, options);
  }

  /**
   * Applies the filter function 
   */
  applyFilter() {
    [...]
  }

  /**
   * Attach the data
   */
  attach() {
    [...]
  }

  /**
   * Remove the data
   */
  detach() {
    [...]
  }
}

```

### JSDoc configuration

```js
{
  "plugins": ["node_modules/jsdoc-babel"],
  "babel": {
    "plugins": [
      "transform-class-properties",
      "transform-flow-strip-types",
      "transform-object-rest-spread",
      ["transform-react-jsx", {"pragma": "h"}]
    ],
    "babelrc": false
  }
}
```

### JSDoc debug output

```
{ JSDOC_ERROR: DEBUG: JSDoc 3.5.5 (Thu, 14 Sep 2017 02:51:54 GMT)
    at Explain.verifyOutput (/Users/danielbechler/Documents/Projects/meteogroup-weathermap/packages/tools/node_modules/jsdoc-api/lib/jsdoc-command.js:113:19)
    at ChildProcess.handle.on.code (/Users/danielbechler/Documents/Projects/meteogroup-weathermap/packages/tools/node_modules/jsdoc-api/lib/explain.js:48:38)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at maybeClose (internal/child_process.js:921:16)
    at Socket.stream.socket.on (internal/child_process.js:348:11)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at Pipe._handle.close [as _onclose] (net.js:549:12) name: 'JSDOC_ERROR' }
(node:79423) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: JSDOC_ERROR: DEBUG: JSDoc 3.5.5 (Thu, 14 Sep 2017 02:51:54 GMT)
(node:79423) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Done in 7.35s.
```

### Expected behavior

I expect output to be generated for the methods `attach`, `detach` and `applyFilter`.

### Current behavior

There is no output generated for these methods at all.

### Your environment

| Software         | Version
| ---------------- | -------
| JSDoc            | ^3.5.3
| Node.js          | 8.2.1
| npm              | 5.5.1
| Operating system | MacOS Sierra 10.12.6

**Comment by lll000111** [comment]
Could be similar to the issue of @babel/transform-plugin-typescript. I don't know, just guessing and bringing this up based on that it works when you pre-strip the types, which presumably uses a different parser than Babel(?). The AST method `someNode.remove()` used by Babel and in those plugins in some cases removes comments preceding the node together with the node, so they are just gone for the next step in the pipe. For reference: https://github.com/babel/babel/issues/9916 -- Just in case this is a similar issue.
