### ISSUE TITLE
Executing JSDoc on angular.mins.js fails due to JavaScript Memory Error

### ISSUE THREAD

**Issue by mikegwhit** [jsdoc/jsdoc#1583]
This happens on Windows.

### Input code
```
FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: node_module_register
 2: v8::internal::FatalProcessOutOfMemory
 3: v8::internal::FatalProcessOutOfMemory
 4: v8::internal::Factory::NewRawTwoByteString
 5: v8::internal::Smi::SmiPrint
 6: v8::internal::StackGuard::HandleInterrupts
 7: v8::internal::RegExpImpl::Exec
 8: v8::internal::RegExpImpl::Exec
 9: v8::internal::interpreter::BytecodeArrayRandomIterator::UpdateOffsetFromIndex
10: 000002FD5B6043C1

    at ChildProcess.exithandler (child_process.js:276:12)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:915:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
  killed: false,
  code: 3,
  signal: null,
```

### Expected behavior

It should not crash.

### Current behavior

It crashes.

### Your environment

| Software         | Version
| ---------------- | -------
| JSDoc            | 3.5
| Node.js          | 10.x
| npm              | 6.4.x
| Operating system | Windows

**Comment by hegemonic** [comment]
I'm guessing that a minified version of Angular is not something that JSDoc could turn into useful documentation. But you're right, JSDoc shouldn't crash just because the input file is large.

That said: Lots of stuff in JSDoc is predicated on using synchronous I/O, plus the assumption that we can read each input file into memory in its entirety. Unwinding those assumptions would take a lot of work, and it would break many things. (That doesn't mean that this bug should never be fixed, but it does mean that it's unlikely to be fixed anytime soon.)
