### ISSUE TITLE
Empty @throws tag crashes jsdoc

### ISSUE THREAD

**Issue by yudanli** [jsdoc/jsdoc#1584]
```js
   /**
     * @function
     * Test function
     * @throws
     */
   function func () {
        return true;
    };
```

### JSDoc configuration

Default config.

### JSDoc debug output

```
ERROR: The @throws tag requires a value. File: test.js, line: 9
undefined:10
 if (data.description && data.type && data.type.names) {
          ^

TypeError: Cannot read property 'description' of undefined
    at exports.Template.eval (eval at _.template (D:\projects\jsdoc\node_modules\underscore\underscore.js:1454:20), <anonymous>:10:11)
    at exports.Template.template (D:\projects\jsdoc\node_modules\underscore\underscore.js:1461:21)
    at exports.Template.partial (D:\projects\jsdoc\lib\jsdoc\template.js:55:29)
    at eval (eval at _.template (D:\projects\jsdoc\node_modules\underscore\underscore.js:1454:20), <anonymous>:141:14)
    at Array.forEach (<anonymous>)
    at exports.Template.eval (eval at _.template (D:\projects\jsdoc\node_modules\underscore\underscore.js:1454:20), <anonymous>:139:16)
    at exports.Template.template (D:\projects\jsdoc\node_modules\underscore\underscore.js:1461:21)
    at exports.Template.partial (D:\projects\jsdoc\lib\jsdoc\template.js:55:29)
    at eval (eval at _.template (D:\projects\jsdoc\node_modules\underscore\underscore.js:1454:20), <anonymous>:236:14)
    at Array.forEach (<anonymous>)
    at eval (eval at _.template (D:\projects\jsdoc\node_modules\underscore\underscore.js:1454:20), <anonymous>:234:10)
    at Array.forEach (<anonymous>)
    at exports.Template.eval (eval at _.template (D:\projects\jsdoc\node_modules\underscore\underscore.js:1454:20), <anonymous>:10:10)
    at exports.Template.template (D:\projects\jsdoc\node_modules\underscore\underscore.js:1461:21)
    at exports.Template.partial (D:\projects\jsdoc\lib\jsdoc\template.js:55:29)
    at exports.Template.render (D:\projects\jsdoc\lib\jsdoc\template.js:69:24)
```

### Expected behavior

The parsing error should not cause crashes. 

With the current jsdoc code, when @throws is parsed without a value, the data.exceptions passed to method.tmpl will be [null]. When the null is further passed to exception.tmpl, the crash happens.   

My debugging shows that the error could be quenched with a sanity check in definitions.js::throws.onTagged:

```js
        onTagged: function(doclet, tag) {
            doclet.exceptions = doclet.exceptions || [];
            doclet.exceptions.push(tag.value);
        },
```

Don't know if it should be fixed even earlier in the callstack.

### Your environment

| Software         | Version
| ---------------- | -------
| JSDoc            | 3.6.0-dev
| Node.js          | 8.11.1
| npm              | 5.6.0
| Operating system |
Win 10

**Comment by lll000111** [comment]
So... just write `@throws {Error}`? Seems like an easy fix. Looking at

http://usejsdoc.org/tags-throws.html

a text or an error type is mandatory and not optional. Which really is not a limitation.

**Comment by hegemonic** [comment]
I agree that JSDoc shouldn't crash in this situation.
