### ISSUE TITLE
Cannot read property 'constructor' of null.

### ISSUE THREAD

**Issue by Floffah** [jsdoc/jsdoc#1625]
### Input code

Not sure what to put here so i will put everything
```js
module.exports = function (grunt) {
  grunt.initConfig({
    pkg: grunt.file.readJSON('package.json'),
    jsdoc: {
      dist: {
        src: ['src/**/*.js', 'README.md'],
        options: {
          template: "node_modules/foodoc/template",
          configure: "node_modules/foodoc/template/conf.json",
          "destination": "./docs"
        }
      }
    }
  });
  grunt.loadNpmTasks('grunt-jsdoc');
  grunt.registerTask('default', ['jsdoc']);
}
```

```js
class StringManip {
    /**
     * The string you want to manipulate.
     * @param {String} string 
     */
    constructor(string) {
        this._string = string;
    }

    /**
     * Returns the string you inputted but the first alphabetic letter of the string is uppercase.
     * @returns {String}
     */
    firstLetterUpperCase() {

    }
}

module.exports = StringManip;
```
```js
export as namespace Nodon;

export class StringManip {
    //A class with many string manipulation functions.
    constructor(string: String);
    //Returns the string you inputted but the first alphabetic letter of the string is uppercase.
    firstLetterUpperCase(): String;
}

declare var StringManip: StringManip;
```
```js
module.exports = {
    StringManip: require('./src/StringManip')
};
```
```js
const {StringManip} = require('../');

const stringmanip = new StringManip('test string');
stringmanip.firstLetterUpperCase();
```

### JSDoc configuration

```js
{
    "tags": {
      "allowUnknownTags": true
    },
    "plugins": ["plugins/markdown"],
    "templates": {
      "includeDate": true,
      "dateFormat": "Do MMM YYYY",
      "systemName": "FooDoc",
      "systemSummary": "A Bootstrap and Handlebars based JSDoc3 template.",
      "systemLogo": "",
      "systemColor": "",
      "copyright": "FooDoc Copyright © 2016 The contributors to the JSDoc3 and FooDoc projects.",
      "linenums": true,
      "collapseSymbols": true,
      "inverseNav": true,
      "inlineNav": false,
      "outputSourceFiles": true,
      "outputSourcePath": false,
      "disablePackagePath": true,
      "methodHeadingReturns": true,
      "showTableOfContents": true,
      "showAccessFilter": false,
      "sort": "linenum, longname, version, since",
      "search": true,
      "analytics": {"ua": null, "domain": null},
      "favicon": null,
      "stylesheets": [],
      "scripts": []
    },
    "markdown": {
      "parser": "gfm",
      "hardwrap": true
    }
  }
  
```

### JSDoc debug output

On console.
```
Running "jsdoc:dist" (jsdoc) task
>> Cannot parse the config file node_modules/foodoc/template/conf.json: TypeError: Cannot read property 'constructor' of null
>> Exiting JSDoc because an error occurred. See the previous log messages for details.
Warning: jsdoc terminated with a non-zero exit code Use --force to continue.
```

In log files.
```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\***\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'compiledocs' ]
2 info using npm@6.9.0
3 info using node@v11.11.0
4 verbose run-script [ 'precompiledocs', 'compiledocs', 'postcompiledocs' ]
5 info lifecycle ***@1.0.0~precompiledocs: ***@1.0.0
6 info lifecycle ***@1.0.0~compiledocs: ***@1.0.0
7 verbose lifecycle ***@1.0.0~compiledocs: unsafe-perm in lifecycle true
8 verbose lifecycle ***@1.0.0~compiledocs: PATH: C:\Users\***\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;E:\projects\unfinished\libary\***\node_modules\.bin;C:\Python27\;C:\Python27\Scripts;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Program Files (x86)\Razer\ChromaBroadcast\bin;C:\Program Files\Razer\ChromaBroadcast\bin;C:\ProgramData\Boxstarter;C:\Program Files (x86)\Razer Chroma SDK\bin;C:\Program Files\Razer Chroma SDK\bin;C:\ProgramData\scoop\shims;C:\Program Files\Microsoft MPI\Bin\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\ProgramData\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Dell\Dell Data Protection\Drivers\TSS\bin\;C:\Program Files\Dell\Dell Data Protection\Encryption\;C:\Program Files (x86)\GtkSharp\2.12\bin;C:\Gradle\gradle-4.7\bin;C:\Program Files (x86)\Java\jdk1.8.0_172\bin;C:\cygnus\cygwin-b20\H-i586-cygwin32\bin;C:\Program Files (x86)\GnuWin32\bin;C:\Program Files\dotnet\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\WINDOWS\System32\OpenSSH\;C:\WINDOWS\system32\config\systemprofile\.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm\;C:\PHP;C:\Program Files\ffmpeg\bin;C:\Program Files\ffmpeg;C:\PostgreSQL\pg10\bin;C:\Program Files (x86)\PuTTY\;C:\Program Files\Git\cmd;C:\Users\***\AppData\Local\Microsoft\WindowsApps;C:\Users\***\.dotnet\tools;C:\ProgramData\chocolatey\bin;C:\Python27;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;c:\Program Files\Oracle\VirtualBox;C:\Users\***\AppData\Roaming\npm;C:\Users\***\AppData\Local\Yarn\bin;C:\Program Files\nodejs\;C:\Program Files (x86)\Yarn\bin\;C:\Users\***\AppData\Roaming\Dashlane\6.1844.0.14689\bin\Firefox_Extension\{442718d9-475e-452a-b3e1-fb1ee16b8e9f}\components;C:\Users\***\AppData\Roaming\Dashlane\6.1844.0.14689\ucrt;C:\Users\***\AppData\Roaming\Dashlane\6.1844.0.14689\bin\Qt;C:\Users\***\AppData\Roaming\Dashlane\6.1844.0.14689\bin\Ssl;C:\Users\***\AppData\Roaming\Dashlane\6.1848.0.15588\bin\Firefox_Extension\{442718d9-475e-452a-b3e1-fb1ee16b8e9f}\components;C:\Users\***\AppData\Roaming\Dashlane\6.1848.0.15588\ucrt;C:\Users\***\AppData\Roaming\Dashlane\6.1848.0.15588\bin\Qt;C:\Users\***\AppData\Roaming\Dashlane\6.1848.0.15588\bin\Ssl;C:\Users\***\AppData\Local\GitHubDesktop\bin;C:\Users\***\AppData\Local\Microsoft\WindowsApps;C:\Users\***\AppData\Roaming\Dashlane\6.1907.0.17833\bin\Firefox_Extension\{442718d9-475e-452a-b3e1-fb1ee16b8e9f}\components;C:\Users\***\AppData\Roaming\Dashlane\6.1907.0.17833\ucrt;C:\Users\***\AppData\Roaming\Dashlane\6.1907.0.17833\bin\Qt;C:\Users\***\AppData\Roaming\Dashlane\6.1907.0.17833\bin\Ssl;C:\Users\***\AppData\Roaming\npm;C:\Users\***\AppData\Local\Yarn\bin;C:\Users\***\AppData\Local\Programs\Microsoft VS Code Insiders\bin
9 verbose lifecycle ***@1.0.0~compiledocs: CWD: E:\projects\unfinished\libary\***
10 silly lifecycle ***@1.0.0~compiledocs: Args: [ '/d /s /c',
10 silly lifecycle   'jsdoc -c jsdocconf.json -t ./node_modules/foodoc/template -R README.md -r .' ]
11 silly lifecycle ***@1.0.0~compiledocs: Returned: code: 1  signal: null
12 info lifecycle ***@1.0.0~compiledocs: Failed to exec compiledocs script
13 verbose stack Error: ***@1.0.0 compiledocs: `jsdoc -c jsdocconf.json -t ./node_modules/foodoc/template -R README.md -r .`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Users\***\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:197:13)
13 verbose stack     at ChildProcess.<anonymous> (C:\Users\***\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:197:13)
13 verbose stack     at maybeClose (internal/child_process.js:984:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:265:5)
14 verbose pkgid ***@1.0.0
15 verbose cwd E:\projects\unfinished\libary\***
16 verbose Windows_NT 10.0.17763
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\***\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "compiledocs"
18 verbose node v11.11.0
19 verbose npm  v6.9.0
20 error code ELIFECYCLE
21 error errno 1
22 error ***@1.0.0 compiledocs: `jsdoc -c jsdocconf.json -t ./node_modules/foodoc/template -R README.md -r .`
22 error Exit status 1
23 error Failed at the ***@1.0.0 compiledocs script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```
*** is a censored name or project name.

### Expected behavior

Compiles docs with default template options

### Current behavior
Erroring because "cannot read property 'constructor' of null". Nothing in the docs about defining a constructor of anything. 

### Your environment

| Software         | Version
| ---------------- | -------
| JSDoc            | latest (latest of latest not latest of recommended)
| Node.js          | latest (latest of latest not latest of recommended)
| npm              | latest (latest of latest not latest of recommended)
| Operating system | Windows 10 (complete latest)

### Comments
I only have a few files since i just started writing this library but all of them work. 
**before anyone asks** yes i tried it without grunt and i get the exact same outcome.

**Comment by hegemonic** [comment]
I can't tell what version of JSDoc you're using. Can you please upgrade to version 3.6.1 and try again?

If it still doesn't work, please try generating the docs with JSDoc's default template, to rule out template issues.

If it _still_ doesn't work, please run JSDoc on its own, with the `--debug` flag, and provide the debug output.

**Comment by Floffah** [comment]
doesn't matter now, figured it out multiple weeks ago.

**Comment by jackthehack21** [comment]
@Floffah what was it, im getting that with foodoc as well.

**Comment by ArkinSolomon** [comment]
How did you fix this?

**Comment by garrettmorse** [comment]
@ArkinSolomon I believe this was an issue due to null values being present in jsdoc.json. I fixed this issue by making the following change.
 
![Screen Shot 2022-08-25 at 1 10 11 PM](https://user-images.githubusercontent.com/47065587/186727756-3b9babda-098e-4888-a4c1-96e39a1d16dc.png)
