### ISSUE TITLE
Error while documenting in static inner classes

### ISSUE THREAD

**Issue by SukantPal** [jsdoc/jsdoc#1673]
JSDoc fails while parsing the code I've shown below.

### Input code

```js
class ParentClass {
  /**
   * Documentation
   */
  static InnerClass = class {
  }
}
```

### JSDoc debug output

```
TypeError: Cannot read property 'memberof' of null
    at Parser.astnodeToMemberof (/Users/shukantpal/Web Projects/jsdoc-bug-static-inner-class/node_modules/jsdoc/lib/jsdoc/src/parser.js:392:24)
    at addSymbolMemberof (/Users/shukantpal/Web Projects/jsdoc-bug-static-inner-class/node_modules/jsdoc/lib/jsdoc/src/handlers.js:268:31)
    at newSymbolDoclet (/Users/shukantpal/Web Projects/jsdoc-bug-static-inner-class/node_modules/jsdoc/lib/jsdoc/src/handlers.js:298:13)
    at Parser.<anonymous> (/Users/shukantpal/Web Projects/jsdoc-bug-static-inner-class/node_modules/jsdoc/lib/jsdoc/src/handlers.js:365:13)
    at Parser.emit (events.js:203:13)
    at Visitor.visitNode (/Users/shukantpal/Web Projects/jsdoc-bug-static-inner-class/node_modules/jsdoc/lib/jsdoc/src/visitor.js:849:20)
    at Visitor.visit (/Users/shukantpal/Web Projects/jsdoc-bug-static-inner-class/node_modules/jsdoc/lib/jsdoc/src/visitor.js:759:21)
    at Walker.recurse (/Users/shukantpal/Web Projects/jsdoc-bug-static-inner-class/node_modules/jsdoc/lib/jsdoc/src/walker.js:694:42)
    at Parser._walkAst (/Users/shukantpal/Web Projects/jsdoc-bug-static-inner-class/node_modules/jsdoc/lib/jsdoc/src/parser.js:305:22)
    at Parser._parseSourceCode (/Users/shukantpal/Web Projects/jsdoc-bug-static-inner-class/node_modules/jsdoc/lib/jsdoc/src/parser.js:296:22)
    at Parser.parse (/Users/shukantpal/Web Projects/jsdoc-bug-static-inner-class/node_modules/jsdoc/lib/jsdoc/src/parser.js:202:22)
    at Object.module.exports.cli.parseFiles (/Users/shukantpal/Web Projects/jsdoc-bug-static-inner-class/node_modules/jsdoc/cli.js:365:46)
    at module.exports.cli.main (/Users/shukantpal/Web Projects/jsdoc-bug-static-inner-class/node_modules/jsdoc/cli.js:234:18)
    at Object.module.exports.cli.runCommand (/Users/shukantpal/Web Projects/jsdoc-bug-static-inner-class/node_modules/jsdoc/cli.js:186:9)
    at /Users/shukantpal/Web Projects/jsdoc-bug-static-inner-class/node_modules/jsdoc/jsdoc.js:93:9
    at Object.<anonymous> (/Users/shukantpal/Web Projects/jsdoc-bug-static-inner-class/node_modules/jsdoc/jsdoc.js:94:3)
```

### Your environment

| Software         | Version
| ---------------- | -------
| JSDoc            | 3.6.3
| Node.js          | (unknown)
| npm              | (unknown)
| Operating system | macOS Mojave

I have created a repository for this bug for your convenience: https://github.com/SukantPal/jsdoc-bug-static-inner-class

**Comment by mariusmaydev** [comment]
well, i have the same problem... please help!

**Comment by ShukantPal** [comment]
Use https://github.com/webdoc-labs/webdoc - I wrote it lol

**Comment by nexushoratio** [comment]
I do not have a problem with the current test case, but a minor variation of it, adding a `constructor()` to the inner class, does fail.

```javascript
class Outer {
  static Inner = class {
    constructor() {
      //
    }
  }
}
```

Rename `constructor()` to `ctor()`, and it at least does not crash.

This is from whatever is current running via GH actions.  Which appears to be jsdoc 4.0.5 and node v22.23.1

```
/usr/local/lib/node_modules/jsdoc/lib/jsdoc/src/parser.js:392
            if (doclet.memberof) {
                       ^

TypeError: Cannot read properties of null (reading 'memberof')
    at Parser.astnodeToMemberof (/usr/local/lib/node_modules/jsdoc/lib/jsdoc/src/parser.js:392:24)
    at addSymbolMemberof (/usr/local/lib/node_modules/jsdoc/lib/jsdoc/src/handlers.js:268:31)
    at newSymbolDoclet (/usr/local/lib/node_modules/jsdoc/lib/jsdoc/src/handlers.js:298:13)
    at Parser.<anonymous> (/usr/local/lib/node_modules/jsdoc/lib/jsdoc/src/handlers.js:365:13)
    at Parser.emit (node:events:519:28)
    at Visitor.visitNode (/usr/local/lib/node_modules/jsdoc/lib/jsdoc/src/visitor.js:846:20)
    at Visitor.visit (/usr/local/lib/node_modules/jsdoc/lib/jsdoc/src/visitor.js:756:21)
    at Walker.recurse (/usr/local/lib/node_modules/jsdoc/lib/jsdoc/src/walker.js:694:42)
    at Parser._walkAst (/usr/local/lib/node_modules/jsdoc/lib/jsdoc/src/parser.js:305:22)
    at Parser._parseSourceCode (/usr/local/lib/node_modules/jsdoc/lib/jsdoc/src/parser.js:296:22)
    at Parser.parse (/usr/local/lib/node_modules/jsdoc/lib/jsdoc/src/parser.js:202:22)
    at module.exports.cli.parseFiles (/usr/local/lib/node_modules/jsdoc/cli.js:365:46)
    at module.exports.cli.main (/usr/local/lib/node_modules/jsdoc/cli.js:234:18)
    at module.exports.cli.runCommand (/usr/local/lib/node_modules/jsdoc/cli.js:186:9)
    at /usr/local/lib/node_modules/jsdoc/jsdoc.js:93:9
    at Object.<anonymous> (/usr/local/lib/node_modules/jsdoc/jsdoc.js:94:3)
```

**Comment by nexushoratio** [comment]
I seem to have found a work around.

In the inner class, `@ignore` the class docstring, move the content to the constructor, and use an `@alias`.

```javascript
/**
 * This is the outer class.
 */
class Outer {

  /**
   * @param {string} arg - Be argumentative.
   */
  constructor(arg) {
    this.arg = arg;
  }

  /**
   * This is inner class docstring.
   * @ignore
   */
  static Inner = class {

    /**
     * This is the inner class constructor docstring.
     *
     * @alias Outer.Inner
     * @param {number} init - Initial value.
     */
    constructor(init) {
      this.init = init;
    }

  }

}
```

---

The `@ignore` is necessary so the inner class does not show up as both a class and a member.

It is annoying that one has to move/copy the docstring from the class definition to the constructor, making it inconsistent with how outer classes, and inner classes without constructors are documented.

But, at least it doesn't crash!
