### ISSUE TITLE
Error installing jsdoc

### ISSUE THREAD

**Issue by olegws** [jsdoc/jsdoc#1741]
Error installing jsdoc

### Input code

npm install -g jsdoc

### JSDoc configuration

The configuration file has not yet been created.

### JSDoc debug output

...
npm http GET https://registry.npmjs.org/taffydb/-/taffydb-2.6.2.tgz
npm http 405 https://registry.npmjs.org/babel/parser
npm http 200 https://registry.npmjs.org/strip-json-comments/-/strip-json-comments-3.0.1.tgz
npm http GET https://registry.npmjs.org/bluebird/-/bluebird-3.7.2.tgz
npm ERR! TypeError: Cannot read property 'latest' of undefined
npm ERR!     at next (/usr/lib/node_modules/npm/lib/cache.js:687:35)
npm ERR!     at /usr/lib/node_modules/npm/lib/cache.js:675:5
npm ERR!     at saved (/usr/lib/node_modules/npm-registry-client/lib/get.js:148:7)
npm ERR!     at /usr/lib/node_modules/graceful-fs/polyfills.js:133:7
npm ERR!     at Object.oncomplete (fs.js:108:15)
...

### Your environment

| Software         | Version
| ---------------- | -------
| JSDoc            |  uploaded npm
| Node.js          |  nodejs-0.10.48-3.el6.x86_64
| npm              |  npm-1.3.6-5.el6.noarch
| Operating system | Centos 64-bit 6.10

**Comment by hegemonic** [comment]
You're using an ancient version of Node.js. Please upgrade.
