### ISSUE TITLE
npm test fails on git clone of repository

### ISSUE THREAD

**Issue by pentacular** [jsdoc/jsdoc#1800]
Forking the repository, then cloning, installing and running npm test crashes.

```
// fork jsdoc to https://github.com/pentacular/jsdoc
git clone https://github.com/pentacular/jsdoc
cd jsdoc
npm install
npm test
```

```
npm test

> jsdoc@ test /github10/jsdoc
> gulp

[15:42:40] Using gulpfile /github10/jsdoc/gulpfile.js
[15:42:40] Starting 'default'...
[15:42:40] Starting 'lint'...
[15:42:45] Finished 'lint' after 4.5 s
[15:42:45] Starting 'test'...
[15:42:45] 'test' errored after 523 ms
[15:42:45] Error: exited with error code: 1
    at ChildProcess.onexit (/github10/jsdoc/node_modules/end-of-stream/index.js:39:36)
    at ChildProcess.emit (events.js:305:20)
    at ChildProcess.EventEmitter.emit (domain.js:545:15)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
[15:42:45] 'default' errored after 5.03 s
npm ERR! Test failed.  See above for more details.

```
### JSDoc configuration

https://github.com/pentacular/jsdoc/commit/9142fe8858a919332fbc8eb7c08c376ff70d35a5

```
Your debug output here
```

### Expected behavior

npm test on a fresh clone should not fail.

### Current behavior

npm test on a fresh clone fails. :)

### Your environment

| Software         | Version
| ---------------- | -------
| JSDoc            |
| Node.js          | v13.5.0
| npm              | 6.13.4
| Operating system | debian

**Comment by pentacular** [comment]
Eventually I thought, "surely the online tests are working, how does travis manage to build this."

So I looked in .travis.yml and ran:
```
npm install -g gulp lerna && npm install && lerna bootstrap
```

And now npm test works.
I will leave this issue open for future readers.

But it would been nice for this to be mentioned in the README.md. :)
