### ISSUE TITLE
Clarification JSDoc Spec: Function parameter / argument names

### ISSUE THREAD

**Issue by m-jung** [jsdoc/jsdoc#1955]
It seems to be unclear if named function parameters (eg. `function(arg0: AType, arg1: BType)` as opposed to `function(AType, BType)`) are supported by the spec or not.

I am aware that [catharsis](https://github.com/hegemonic/catharsis/) actually parses JSDoc, but before i file a bug / feature request, i'd like to know how the intended behavior is.

TL;DR
Make a clear statement for the support of named function parameters by JSDoc.

### Input code

```js
/**
 * @param {function(arg0:AType, arg1:BType)} // Does not throw
 * @param {function(arg0: AType, arg1: BType)} // Throws
 */
```

### catharsis output

```
SyntaxError: Expected "$", "'", ".", "0", "@", "\"", "\\", "_", "break", "case", "catch", "class", "const", "continue", "debugger", "default", "delete", "do", "else", "enum", "export", "extends", "finally", "for", "function", "if", "implements", "import", "in", "instanceof", "interface", "let", "new", "package", "private", "protected", "public", "return", "static", "super", "switch", "this", "throw", "try", "typeof", "var", "void", "while", "with", "yield", Unicode letter number, Unicode lowercase letter, Unicode modifier letter, Unicode other letter, Unicode titlecase letter, Unicode uppercase letter, or [1-9] but " " found.

    at peg$buildStructuredError (node_modules\catharsis\lib\parser.js:971:12)
    at peg$parse (node_modules\catharsis\lib\parser.js:5763:11)
    at cachedParse (node_modules\catharsis\catharsis.js:88:22)
    at Catharsis.parse (node_modules\catharsis\catharsis.js:147:16)
    at Context.<anonymous> (test\catharsis.spec.js:180:70)
    at processImmediate (internal/timers.js:439:21)
```

### Expected behavior

Either named function parameters are supported, then their presence should'nt raise errors, separated by spaces or not.
Or named function parameters are not supported, then always an error should be raised.

If the former is the case, I would expect a description like the following:
```js
{
    type: 'FunctionType',
    params: [
        {
            name: 'arg0',
            type: 'ParameterType',
            value: { name: 'AType', type: 'NameExpression' }
        },
        {
            name: 'arg1',
            type: 'ParameterType',
            value: { name: 'BType', type: 'NameExpression' }
        }
    ],
}
```

The **currently non existent** `ParameterType` would behave much like the `RecordType`, but `name` could be omitted.
`value` would contain any other type. This way more complex definitions are possible too.

`function(arg0: AType|BType, arg1: Generic<CType|DType>)` would lead to:

```js
{
    type: 'FunctionType',
    params: [
        {
            name: 'arg0',
            type: 'ParameterType',
            value: {
                type: 'TypeUnion',
                elements: [
                    { name: 'AType', type: 'NameExpression' },
                    { name: 'BType', type: 'NameExpression' }
                ]
            }
        },
        {
            name: 'arg1',
            type: 'ParameterType',
            value: {
                type: 'TypeApplication',
                expression: { name: 'Generic', type: 'NameExpression' },
                applications: [{
                    type: 'TypeUnion',
                    elements: [
                        { name: 'CType', type: 'NameExpression' },
                        { name: 'DType', type: 'NameExpression' }
                    ]
                }],
            }
        }
    ]
}
```

### Current behavior

Currently defining named parameters **without** spaces, catharsis does not throw an error but returns an (wrong?) description.
This leads me to the asumption, that this feature is not supported and the returned description is an bug.
I think the description is wrong, or at least not sufficient, since `name` (normally the Type) includes the parameter's name too.

```js
{
    type: 'FunctionType',
    params: [
        {
            name: "arg0:AType",
            type: "NameExpression"
        },
        {
            name: "arg1:BType",
            type: "NameExpression"
        }
    ]
}
```
The output HTML misses the Types in any case (named or unnamed):
Is: `function`
Expected: `function(l: T|Array<T>|Iterable<T>, r: T|Array<T>|Iterable<T>)`
![image](https://user-images.githubusercontent.com/69465576/142019770-e651765d-da70-434f-9092-257d20d2a36c.png)

Defining named parameters **with** spaces, catharsis will raise the an `SyntaxError`.

### Your environment

| Software         | Version |
| ---------------- | ------- |
| JSDoc            | 6.3.7
| Node.js          | 12.15.0
| npm              | 8.1.3
| Operating system | Windows

**Comment by akudev** [comment]
Just stumbled across this when researching the parser behavior with no space after colon in RecordTypes. Just a hint:
```
@param {function(arg0:AType, arg1:BType)} 
```
without spaces is apparently not being parsed as named function parameters, but as two type names which happen to contain a colon. First argument has type "arg0:AType", the second has type "arg1:BType". 
Which looks odd to me, as I would have expected the space to be non-significant and the colon not to be a legal property name character.
