### ISSUE TITLE
Release 3.6.8 fails to install

### ISSUE THREAD

**Issue by RomanKisilenko** [jsdoc/jsdoc#1970]
### Expected behavior
Package is installed correctly via npm

### Current behavior
```
> jsdoc@3.6.8 preinstall /builds/xxx/xxx/node_modules/jsdoc
> npx npm-force-resolutions
npx: installed 6 in 3.256s
Error: ENOENT: no such file or directory, open './package-lock.json'
    at Object.openSync (fs.js:448:3)
    at Object.fs [as readFileSync] (fs.js:348:35)
    at npm_force_resolutions$core$node_slurp (/root/.npm/_npx/144/lib/node_modules/npm-force-resolutions/out/npm_force_resolutions/core.cljs:15:20)
    at npm_force_resolutions$core$read_json (/root/.npm/_npx/144/lib/node_modules/npm-force-resolutions/out/npm_force_resolutions/core.cljs:22:23)
    at switch__2144__auto__ (/root/.npm/_npx/144/lib/node_modules/npm-force-resolutions/out/npm_force_resolutions/core.cljs:151:3)
    at /root/.npm/_npx/144/lib/node_modules/npm-force-resolutions/out/npm_force_resolutions/core.cljs:151:3
    at npm_force_resolutions$core$update_package_lock_$_state_machine__2145__auto____1 (/root/.npm/_npx/144/lib/node_modules/npm-force-resolutions/out/npm_force_resolutions/core.js:648:4)
    at cljs.core.async.impl.ioc-helpers/FN-IDX (/root/.npm/_npx/144/lib/node_modules/npm-force-resolutions/out/npm_force_resolutions/core.js:664:88)
    at cljs.core.async.impl.ioc-helpers/run-state-machine (/root/.npm/_npx/144/lib/node_modules/npm-force-resolutions/out/cljs/core/async/impl/ioc_helpers.cljs:35:23)
    at cljs$core$async$impl$ioc_helpers$run_state_machine_wrapped (/root/.npm/_npx/144/lib/node_modules/npm-force-resolutions/out/cljs/core/async/impl/ioc_helpers.cljs:39:6)
```

### Your environment

| Software         | Version |
| ---------------- | ------- |
| JSDoc            | 3.6.8 |
| Node.js          | 10.x |

**Comment by hegemonic** [comment]
Thanks for the heads up! I just published JSDoc 3.6.9 to fix this issue.

Unfortunately, for some reason, `npm install jsdoc@3.6.9` currently fails. Hopefully the update is just propagating and will be available via `npm install` soon.
