### ISSUE TITLE
jsdoc unexpected token leads to JSDoc not finding files

### ISSUE THREAD

**Issue by davesargrad** [jsdoc/jsdoc#1987]
js-doc is invoked as part of the [sphinx-js](https://github.com/mozilla/sphinx-js) tooling. Sphinx complains about jsdoc not finding "js" files in a directory that contains valid js files.

It seems that this is a jsdoc configuration issue (or perhaps a babel configuration issue), since in the following I see an invalid token and an indication that this is the destructuring syntax "..." that is the problem.
```
(docs) [dsargrad@sdbie-sargrad docs]$ make html
Running Sphinx v4.5.0
/home/dsargrad/.conda/envs/docs/lib/node_modules/jsdoc/node_modules/mkdirp/lib/opts-arg.js:7
    opts = { mode: 0o777, fs, ...opts }
                              ^^^

SyntaxError: Unexpected token ...
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at Object.load (/home/dsargrad/.conda/envs/docs/lib/node_modules/jsdoc/node_modules/requizzle/lib/loader.js:105:18)
    at Requizzle.requizzle (/home/dsargrad/.conda/envs/docs/lib/node_modules/jsdoc/node_modules/requizzle/lib/requizzle.js:87:31)
    at infectProxy (/home/dsargrad/.conda/envs/docs/lib/node_modules/jsdoc/node_modules/requizzle/lib/loader.js:79:31)
    at Module.targetModule.require.filepath [as require] (/home/dsargrad/.conda/envs/docs/lib/node_modules/jsdoc/node_modules/requizzle/lib/loader.js:97:44)
    at require (internal/module.js:20:19)

Sphinx error:
jsdoc found no JS files in the directories ['/home/dsargrad/dev/ves']. Make sure js_source_path is set correctly in conf.py. It is also possible (though unlikely) that jsdoc emitted invalid JSON.
make: *** [html] Error 2

```

How can I determine if this is a jsdoc configuration issue, or a sphinx issue?

I am using jsdoc version 3.6.0.

![image](https://user-images.githubusercontent.com/48793689/164001544-853b4ee6-2905-4cab-9c9e-38909433fed9.png)

I'm also using sphinx (4.5.0) and sphinx-js (3.1.2)
![image](https://user-images.githubusercontent.com/48793689/164001617-a325f85a-7f39-40b3-9f64-cf1fdeb9cb31.png)

**Comment by davesargrad** [comment]
I've verified that even with a small program I see this as a jsdoc "issue":
```
(docs) [dsargrad@sdbie-sargrad test]$ jsdoc main.js 
/home/dsargrad/.conda/envs/docs/lib/node_modules/jsdoc/node_modules/mkdirp/lib/opts-arg.js:7
    opts = { mode: 0o777, fs, ...opts }
                              ^^^

SyntaxError: Unexpected token ...
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at Object.load (/home/dsargrad/.conda/envs/docs/lib/node_modules/jsdoc/node_modules/requizzle/lib/loader.js:105:18)
    at Requizzle.requizzle (/home/dsargrad/.conda/envs/docs/lib/node_modules/jsdoc/node_modules/requizzle/lib/requizzle.js:87:31)
    at infectProxy (/home/dsargrad/.conda/envs/docs/lib/node_modules/jsdoc/node_modules/requizzle/lib/loader.js:79:31)
    at Module.targetModule.require.filepath [as require] (/home/dsargrad/.conda/envs/docs/lib/node_modules/jsdoc/node_modules/requizzle/lib/loader.js:97:44)
    at require (internal/module.js:20:19)

```

```
(docs) [dsargrad@sdbie-sargrad test]$ cat main.js
/** 
 *  A person generator
 * 
 *  @param {string} name The persons full name
 *  @param {number} age The persons age
 *  @param {boolean} isDeveloper The person is a developer
 */
function createPerson(name, age, isDeveloper) {
	return {
		name: name,
		age: age,
		isDeveloper: isDeveloper
	}
}


```

**Comment by JJ** [comment]
Which version of node are you using?

**Comment by hegemonic** [comment]
Yeah, I think this is caused by an outdated version of Node.js.
