### ISSUE TITLE
jsdoc test cases fail with task-runner error: TypeError: Queue is not a constructor

### ISSUE THREAD

**Issue by hartman** [jsdoc/jsdoc#2070]
### Input code

I was trying to run the testcases with `npm run test` on my mac Intel.
Unfortunately the testcases don't complete and report.

```
❯ npm run test

> test
> node_modules/.bin/hereby test

Using ~/Development/jsdoc/Herebyfile.js to run test
Starting test
Error in test in 728ms
Error: Command failed with exit code 1: /Users/hartman/.nvm/versions/node/v18.17.1/bin/node packages/jsdoc/jsdoc.js -T

Executing 1476 defined specs...

>> Done!


Failed Specs:

1. @jsdoc/task-runner/lib/task-runner : is a function
   TypeError: Queue is not a constructor
       at TaskRunner._init file:///Users/hartman/Development/jsdoc/packages/jsdoc-task-runner/lib/task-runner.js:102:19
       at new TaskRunner file:///Users/hartman/Development/jsdoc/packages/jsdoc-task-runner/lib/task-runner.js:35:10
       at UserContext.<anonymous> file:///Users/hartman/Development/jsdoc/packages/jsdoc-task-runner/test/specs/lib/task-runner.js:46:14
       at <Jasmine>

2. @jsdoc/task-runner/lib/task-runner : inherits from emittery
   TypeError: Queue is not a constructor
       at TaskRunner._init file:///Users/hartman/Development/jsdoc/packages/jsdoc-task-runner/lib/task-runner.js:102:19
       at new TaskRunner file:///Users/hartman/Development/jsdoc/packages/jsdoc-task-runner/lib/task-runner.js:35:10
       at UserContext.<anonymous> file:///Users/hartman/Development/jsdoc/packages/jsdoc-task-runner/test/specs/lib/task-runner.js:46:14
       at <Jasmine>


Summary:

❌  Failed
Suites:  524 of 524
Specs:   1455 of 1476 (21 pending)
Expects: 2723 (60 failures)
Finished in 0.231 seconds

Completed test with errors in 776ms
```
etc (60x) 

### Your environment

| Software         | Version |
| ---------------- | ------- |
| JSDoc            | main git
| Node.js          | v18.17.1
| npm              | 9.6.7
| Operating system | macOS Ventura 13.5.1

Anyone any ideas on what is going on here ?

**Comment by hegemonic** [comment]
I can't reproduce this issue, either on my Intel Mac or on GitHub CI.

If you're still seeing this issue, please run these commands while in the repo's root directory and let me know what happens:

```
cd packages/jsdoc-task-runner
node
# And then in the Node.js REPL:
let pQueue = await import('p-queue');
let Queue = pQueue.default;
new Queue();
```
