### ISSUE TITLE
jsdoc fails when ES6 classes have private members (`#fieldname`)

### ISSUE THREAD

**Issue by chfritz** [jsdoc/jsdoc#2091]
jsdoc fails when ES6 classes have private members, i.e., starting with a `#`, which is [broadly supported by browsers and nodejs](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/Private_class_fields#browser_compatibility).

### Input code

```js
/**
 * My class
 * */
class MyClass {

  /**
   * private it is
   * */
  #pssst = 1;
}
```

### JSDoc configuration

None. Just run from command line.

### JSDoc debug output

```
> ~/work/transitive/utils/node_modules/.bin/jsdoc class.js 
/home/cfritz/work/transitive/utils/node_modules/@daybrush/jsdoc/lib/jsdoc/src/visitor.js:377
        e.doclet.access = 'private';
                        ^

TypeError: Cannot set properties of undefined (setting 'access')
    at exports.Parser.<anonymous> (/home/cfritz/work/transitive/utils/node_modules/@daybrush/jsdoc/lib/jsdoc/src/visitor.js:377:25)
    at exports.Visitor.Visitor.visitNode (/home/cfritz/work/transitive/utils/node_modules/@daybrush/jsdoc/lib/jsdoc/src/visitor.js:625:24)
    at exports.Visitor.Visitor.visit (/home/cfritz/work/transitive/utils/node_modules/@daybrush/jsdoc/lib/jsdoc/src/visitor.js:488:27)
    at exports.Walker.Walker.recurse (/home/cfritz/work/transitive/utils/node_modules/@daybrush/jsdoc/lib/jsdoc/src/walker.js:699:38)
    at exports.Parser.Parser._walkAst (/home/cfritz/work/transitive/utils/node_modules/@daybrush/jsdoc/lib/jsdoc/src/parser.js:326:18)
    at exports.Parser.Parser._parseSourceCode (/home/cfritz/work/transitive/utils/node_modules/@daybrush/jsdoc/lib/jsdoc/src/parser.js:317:18)
    at exports.Parser.Parser.parse (/home/cfritz/work/transitive/utils/node_modules/@daybrush/jsdoc/lib/jsdoc/src/parser.js:186:18)
    at Object.module.exports.cli.parseFiles (/home/cfritz/work/transitive/utils/node_modules/@daybrush/jsdoc/cli.js:371:42)
    at module.exports.cli.main (/home/cfritz/work/transitive/utils/node_modules/@daybrush/jsdoc/cli.js:240:14)
    at Object.module.exports.cli.runCommand (/home/cfritz/work/transitive/utils/node_modules/@daybrush/jsdoc/cli.js:190:5)
    at /home/cfritz/work/transitive/utils/node_modules/@daybrush/jsdoc/jsdoc.js:105:9
    at Object.<anonymous> (/home/cfritz/work/transitive/utils/node_modules/@daybrush/jsdoc/jsdoc.js:106:3)
    at Module._compile (node:internal/modules/cjs/loader:1198:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1252:10)
    at Module.load (node:internal/modules/cjs/loader:1076:32)
    at Function.Module._load (node:internal/modules/cjs/loader:911:12)
```

### Expected behavior

No error.

Note that it works once I remove the `#`.

### Current behavior

Error as seen above.

### Your environment

| Software         | Version |
| ---------------- | ------- |
| JSDoc            |  0.4.7
| Node.js          | 16.20.2
| npm              | 8.19.4
| Operating system | ubuntu 20.04

**Comment by tubbo** [comment]
This is happening for me as well. JSDoc is totally ignoring those directives unless I remove the `#` prefix.

**Comment by hegemonic** [comment]
It looks like you're using a fork of JSDoc. Please report this issue to the fork's maintainers.

**Comment by chfritz** [comment]
Sorry, you are right. My bad. It's working in jsdoc (4.0.3).
